# Numpy practice

In [17]:
matrix_1 =[[1,2],[3,4]]
matrix_2 =[[5,6],[7,8]]

result = []
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j] + matrix_2[i][j])
    result.append(tmp)
result

[[6, 8], [10, 12]]

In [25]:
import numpy as np

matrix_1 = np.array(matrix_1)
matrix_2 = np.array(matrix_2)

(matrix_1 + matrix_2).tolist()

[[6, 8], [10, 12]]

In [27]:
matrix_1 = [[1,2],[3,4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_1[i])):
        matrix_1[i][j] += 1
matrix_1

        

[[2, 3], [4, 5]]

In [29]:
matrix_1 = np.array([[1,2],[3,4]])
matrix_1 = matrix_1 + 1
matrix_1.tolist()

[[2, 3], [4, 5]]

In [33]:
import time

size = 10000000

x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+y[i] for i  in range(len(x))]
print("리스트 걸린시간:", time.time() - start_time)

리스트 걸린시간: 1.8591666221618652


In [34]:
##NUMPY를 이용하면 속도가 더 빠르다!

x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("리스트 걸린시간:", time.time() - start_time)

리스트 걸린시간: 0.16201210021972656


In [39]:
x = np.int64([1,2,3,4])
x

array([1, 2, 3, 4], dtype=int64)

In [40]:
y = np.int32([1,2,3,4])
y

array([1, 2, 3, 4])

In [43]:
y.dtype

dtype('int32')

In [45]:
np.float32(y)

array([1., 2., 3., 4.], dtype=float32)

In [48]:
y[0] = 1.1
y

array([1, 2, 3, 4])

In [51]:
x = np.array(1)
print(x.ndim)
print(x.shape)

0
()


In [54]:
x = np.array([1,2,3])
print(x.ndim)
print(x.shape)

1
(3,)


In [58]:
x = np.array([[1,2,3],[4,5,6]])
print(x.ndim)
print(x.shape)
print(x.size)

2
(2, 3)
6


In [60]:
x = np.arange(1,10,0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [64]:
x = np.linspace(1,100,5)
x

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [89]:
x = np.arange(9).reshape(3,-1)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
x = np.arange(9)
x[0:5]

array([0, 1, 2, 3, 4])

In [91]:
x = np.arange(25).reshape(5,-1)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [81]:
x[1:2]

array([[3, 4, 5]])

In [234]:
#slicing 노이해!!!!###

x = np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


In [85]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [87]:
a[[1,1],[1,2]]

array([6, 7])

In [96]:
a[(a>4) & (a<10)]

array([5, 6, 7, 8, 9])

In [109]:
np.random.randint(1,10,size=(5, 5))

array([[1, 9, 1, 6, 2],
       [9, 8, 8, 5, 9],
       [8, 3, 3, 3, 7],
       [2, 5, 7, 7, 2],
       [2, 6, 8, 6, 4]])

In [111]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [125]:
x.ravel(order='F') #결과값이 이상한데??

array([ 0,  5, 10, 15, 20,  1,  6, 11, 16, 21,  2,  7, 12, 17, 22,  3,  8,
       13, 18, 23,  4,  9, 14, 19, 24])

In [129]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [136]:
x = np.arange(9).reshape(3,3)
y = np.arange(9).reshape(3,3)

np.concatenate([x,y], axis =1)


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [140]:
x = np.array([1,2,3,4,5,6])
np.split(x,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [145]:
x = np.arange(16).reshape(4,4)
np.split(x,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [147]:
x = np.array([1,2,3])
x + 1

array([2, 3, 4])

In [152]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,4)
x + y


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [172]:
x = np.arange(16).reshape(4,4)
y = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:
np.any(x>13)

True

In [171]:
np.where(x>4,x,0)

array([[ 0,  0,  0,  0],
       [ 0,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [175]:
np.median(x)

7.5

In [223]:
import numpy as np

x = np.arange(1,10).reshape(3,3)
y = np.arange(10,91,10).reshape(3,3)

print(x+y)
print(np.dot(x,y))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [197]:
x = np.linspace(1,20,30)
x + 10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [228]:
x = np.random.randint(1,100,size=(2,10,10))
x = np.where(x>=50,1,2)
x

array([[[1, 2, 2, 2, 2, 1, 2, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 2, 1],
        [1, 2, 2, 2, 1, 1, 2, 1, 1, 2],
        [1, 2, 2, 2, 1, 1, 1, 2, 2, 1],
        [2, 1, 2, 1, 2, 2, 1, 2, 2, 2],
        [1, 1, 2, 2, 2, 2, 2, 2, 1, 1],
        [1, 1, 1, 1, 2, 2, 1, 2, 1, 2],
        [1, 1, 1, 1, 2, 1, 1, 1, 2, 1],
        [2, 2, 1, 2, 1, 1, 1, 1, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 1, 1, 2]],

       [[1, 2, 2, 1, 2, 1, 2, 1, 2, 1],
        [1, 1, 2, 1, 1, 1, 2, 1, 2, 2],
        [2, 2, 1, 2, 2, 2, 2, 2, 1, 2],
        [1, 2, 2, 2, 2, 2, 2, 1, 2, 1],
        [2, 2, 1, 2, 1, 2, 2, 1, 2, 1],
        [2, 2, 2, 1, 2, 1, 1, 1, 1, 1],
        [1, 1, 2, 2, 1, 2, 2, 1, 1, 1],
        [1, 2, 2, 2, 1, 2, 1, 1, 1, 1],
        [1, 1, 2, 1, 2, 2, 2, 1, 2, 2],
        [1, 1, 2, 2, 2, 1, 1, 1, 2, 1]]])

In [230]:
x[1,5:,5:]

array([[1, 1, 1, 1, 1],
       [2, 2, 1, 1, 1],
       [2, 1, 1, 1, 1],
       [2, 2, 1, 2, 2],
       [1, 1, 1, 2, 1]])