<a href="https://colab.research.google.com/github/Hugekyung/TIL/blob/master/python_basic/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%B2%A0%EC%A0%80%EC%9E%85%EB%AC%B810.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY_2

## 배열의 데이터 타입 변환

In [1]:
import numpy as np

In [2]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [3]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8']) # str타입
num_a1 = str_a1.astype(float) #  str타입을 float타입 변환
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [4]:
num_a1.dtype

dtype('float64')

In [5]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [6]:
num_a2.dtype

dtype('int64')

## 난수 배열의 생성

In [7]:
np.random.rand(2,3) # 0과 1사이의 실수로 난수 배열 생성

array([[0.58044342, 0.55846377, 0.39334641],
       [0.81968614, 0.29668988, 0.4288714 ]])

In [8]:
np.random.rand()

0.8012131082073275

In [9]:
np.random.rand(2,3,4)

array([[[0.85891674, 0.91109301, 0.16706771, 0.88234529],
        [0.3793865 , 0.1349819 , 0.42296404, 0.58389001],
        [0.26464704, 0.61851786, 0.46875073, 0.66974207]],

       [[0.87207773, 0.08414641, 0.04312689, 0.8711474 ],
        [0.21310928, 0.87266148, 0.27505016, 0.54420349],
        [0.22075563, 0.61134353, 0.17379865, 0.00795591]]])

In [10]:
np.random.randint(10, size=(3,4)) # 지정한 범위에 해당하는 정수로 난수 배열을 생성

array([[4, 2, 5, 7],
       [4, 1, 8, 5],
       [2, 5, 7, 7]])

In [11]:
np.random.randint(1,30)

27

## 배열의 연산

### 기본 연산

In [14]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [15]:
arr1 + arr2

array([11, 22, 33, 44])

In [16]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [17]:
arr2*2

array([2, 4, 6, 8])

In [19]:
arr2**2

array([ 1,  4,  9, 16])

In [20]:
arr1*arr2

array([ 10,  40,  90, 160])

In [21]:
arr1/arr2

array([10., 10., 10., 10.])

In [22]:
arr1/(arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [23]:
arr1>20 # 비교 연산을 통해 일치하면 True, 그렇지 않으면 False 반환

array([False, False,  True,  True])

### 통계를 위한 연산

In [24]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [25]:
arr3.sum(), arr3.mean()

(10, 2.0)

In [26]:
arr3.std(), arr3.var() # 표준편차, 분산

(1.4142135623730951, 2.0)

In [28]:
arr3.min(), arr3.max()

(0, 4)

In [29]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [31]:
arr4.cumsum() # 누적합

array([ 1,  3,  6, 10])

In [32]:
arr4.cumprod() # 누적 곱

array([ 1,  2,  6, 24])

### 행렬연산

In [37]:
a = np.array([0,1,2,3,]).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [38]:
b = np.array([3,2,0,1]).reshape(2,2)
b

array([[3, 2],
       [0, 1]])

In [36]:
a.dot(b)

array([[0, 1],
       [6, 7]])

In [39]:
np.dot(a, b)

array([[0, 1],
       [6, 7]])

In [40]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [41]:
a.T

array([[0, 2],
       [1, 3]])

In [42]:
np.linalg.inv(a) # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [43]:
np.linalg.det(a)

-2.0