<a href="https://colab.research.google.com/github/Hugekyung/TIL/blob/master/python_basic/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%B2%A0%EC%A0%80%EC%9E%85%EB%AC%B89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터분석을 위한 패키지

# NUMPY

1. 배열 생성하기

In [1]:
import numpy as np

In [3]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0,1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0. ,  1. ,  5. ,  4. , 12. ,  0.5])

In [8]:
np.array ([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [12]:
d1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
d1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
import pandas as pd
pd.DataFrame(d1)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

2. 범위를 지정해 배열 생성

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(12).reshape(3,4) # reshape(행, 열)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [24]:
b2 = np.arange(5)
b2.shape # 1차원 배열의 경우 (n,)처럼 표시된다

(5,)

In [25]:
np.linspace(1,10,10) # 1부터 10까지 10개의 데이터 생성하기

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(0, np.pi, 20) # 0부터 파이까지 동일한 간격으로 나눈 20개의 데이터 생성하기

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

3. 특별한 형태의 배열 생성

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.eye(3) # 3x3 딘위행렬 생성하기 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])