<a href="https://colab.research.google.com/github/Hugekyung/TIL/blob/master/python_basic/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%B2%A0%EC%A0%80%EC%9E%85%EB%AC%B811.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY_3

## 배열의 인덱싱과 슬라이싱
- 인덱싱 : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱 : 범위를 지정해 배열의 원소를 선택하는 것

In [3]:
# 배열의 인덱싱
import numpy as np

a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [4]:
a1[0]

0

In [5]:
a1[5] = 80

In [6]:
a1

array([ 0, 10, 20, 30, 40, 80])

In [7]:
a1[[1, 3, 4]] # 1차원 배열에서 여러 개의 원소를 선택

array([10, 30, 40])

In [13]:
a2 = np.arange(10,100,10)
a2 = a2.reshape(3,3)

In [14]:
a2[0,2]

30

In [17]:
a2[2,2] = 95

In [19]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [21]:
# 행 전체를 한번에 변경
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [22]:
# 2차원 배열의 여러 원소를 선택
a2[[0,2], [0,1]]

array([10, 80])

In [23]:
# 조건 지정을 통해 배열을 선택
a = np.array([1,2,3,4,5])
a[a>3]

array([4, 5])

In [25]:
a[(a%2) ==0] # 짝수 원소만 반환

array([2, 4])

In [26]:
# 배열의 슬라이싱

b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [27]:
b1[:3]

array([ 0, 10, 20])

In [28]:
b1[2:]

array([20, 30, 40, 50])

In [30]:
b1[2:5] = np.array([25, 35, 45]) # 해당 슬라이싱 위치의 원소 변경
b1

array([ 0, 10, 25, 35, 45, 50])

In [32]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [33]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
b2[1:3, 1:3] # '행시작위치' : '행끝위치' , '열시작위치' : '열끝위치'

array([[50, 60],
       [80, 90]])

In [36]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [39]:
b2[1][0:2] # 행 지정 후 열을 슬라이싱

array([40, 50])

In [40]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])