<a href="https://colab.research.google.com/github/Hugekyung/TIL/blob/master/python_basic/Pandas/Pandas_skills%5B1_3%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas skills  
1. Object Creation  
2. Viewing Data  
3. Selection  
4. Missing Data  
5. Operation  
6. Merge
7. Grouping  
8. Reshapeing  
10. Time Series  
11. Categoricals  
12. Plotting  
13. Getting Data In / Out  
14. Gotchas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Object Creation (객체 생성)

In [5]:
pd.Series([1,3,5,np.nan,6,8])
# 결측지 종류
# None : 누락된 데이터 // NaN : 숫자가 아닌 값

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [7]:
dates = pd.date_range('20200801', periods=6)

### numpy의 np.random.randint(rand/randn)
- np.random.seed : seed를 통한 난수 생성  
- np.random.randint : 균일 분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일 분포에서 난수 matrix array생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 matrix array생성

In [11]:
np.random.randint(6) # 0부터 5까지 랜덤한 숫자 1개 출력

1

In [20]:
np.random.randint(1, 20) # 1부터 19까지 랜덤숫자 1개

18

In [23]:
np.random.rand(6) # 0~1의 균일분포 표준정규분포 난수를 matrix array로 생성

array([0.93904999, 0.59967999, 0.98104284, 0.85661038, 0.54774134,
       0.09362937])

In [22]:
np.random.randn(6) # 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array로 생성

array([ 1.55045578, -0.60029082,  1.73311308, -1.05298294, -1.00379931,
        0.61911294])

In [10]:
np.random.randn(6,4)

array([[-0.62233694, -1.53195266, -0.2249872 , -2.28649086],
       [ 1.00517029, -1.27946364, -0.91808756, -0.73781378],
       [ 0.16417837,  1.34989947,  1.56790988, -1.41330146],
       [ 1.32897881, -0.52492791,  1.37773722, -1.04375474],
       [-0.54624161, -0.00973186, -1.13843371,  0.2696019 ],
       [ 0.49701383,  1.0645552 , -1.74293349,  0.63731514]])

In [ ]:
np.random.rand

In [9]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065

In [25]:
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [30]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

## 2. Viewing Data (데이터 확인하기)

In [32]:
df.head()

A         B         C         D
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753

In [33]:
df.tail()

A         B         C         D
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065

In [34]:
df.index

DatetimeIndex(['2020-08-01', '2020-08-02', '2020-08-03', '2020-08-04',
               '2020-08-05', '2020-08-06'],
              dtype='datetime64[ns]', freq='D')

In [35]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [36]:
df.values

array([[-0.1271627 , -0.04747947, -0.00308918, -0.70201699],
       [-1.61744934, -0.7137447 ,  1.50587781, -0.36367216],
       [ 1.91635181, -1.08053897,  0.32980724, -0.52174771],
       [-0.12750871,  0.24878764, -1.97468725, -0.65277563],
       [ 0.75265359,  1.36640277, -1.47005476, -1.16575328],
       [-0.48041315, -0.80094332, -0.3562877 ,  0.00706483]])

In [39]:
df.describe() # 데이터의 대략적인 통게적 정보를 요약해 보여준다

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.052745 -0.171253 -0.328072 -0.566483
std    1.191769  0.902635  1.258416  0.389110
min   -1.617449 -1.080539 -1.974687 -1.165753
25%   -0.392187 -0.779144 -1.191613 -0.689707
50%   -0.127336 -0.380612 -0.179688 -0.587262
75%    0.532700  0.174721  0.246583 -0.403191
max    1.916352  1.366403  1.505878  0.007065

In [40]:
df.T # Transpose

2020-08-01  2020-08-02  2020-08-03  2020-08-04  2020-08-05  2020-08-06
A   -0.127163   -1.617449    1.916352   -0.127509    0.752654   -0.480413
B   -0.047479   -0.713745   -1.080539    0.248788    1.366403   -0.800943
C   -0.003089    1.505878    0.329807   -1.974687   -1.470055   -0.356288
D   -0.702017   -0.363672   -0.521748   -0.652776   -1.165753    0.007065

In [41]:
df.sort_index(axis=1, ascending=False) # axis=1은 열을 기준으로, ascending=False 내림차순

D         C         B         A
2020-08-01 -0.702017 -0.003089 -0.047479 -0.127163
2020-08-02 -0.363672  1.505878 -0.713745 -1.617449
2020-08-03 -0.521748  0.329807 -1.080539  1.916352
2020-08-04 -0.652776 -1.974687  0.248788 -0.127509
2020-08-05 -1.165753 -1.470055  1.366403  0.752654
2020-08-06  0.007065 -0.356288 -0.800943 -0.480413

In [42]:
df.sort_values(by='B') # B를 기준으로 정렬

A         B         C         D
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753

## 3. Selection (선택)

### Getting (데이터 얻기)

In [43]:
df

A         B         C         D
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065

In [44]:
df['A']

2020-08-01   -0.127163
2020-08-02   -1.617449
2020-08-03    1.916352
2020-08-04   -0.127509
2020-08-05    0.752654
2020-08-06   -0.480413
Freq: D, Name: A, dtype: float64

In [45]:
df[0:3]

A         B         C         D
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748

In [47]:
df['20200802':'20200805']

A         B         C         D
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753

### Selection by Label (Label 을 통한 선택)

In [48]:
df.loc[dates[0]]

A   -0.127163
B   -0.047479
C   -0.003089
D   -0.702017
Name: 2020-08-01 00:00:00, dtype: float64

In [49]:
df.loc[:, ['A','B']] # : 전체 범위에서 A, B columns을 추출

A         B
2020-08-01 -0.127163 -0.047479
2020-08-02 -1.617449 -0.713745
2020-08-03  1.916352 -1.080539
2020-08-04 -0.127509  0.248788
2020-08-05  0.752654  1.366403
2020-08-06 -0.480413 -0.800943

In [50]:
df.loc["20200802":"20200804", ['A','B']]

A         B
2020-08-02 -1.617449 -0.713745
2020-08-03  1.916352 -1.080539
2020-08-04 -0.127509  0.248788

In [51]:
df.loc['20200802',['A','B']]

A   -1.617449
B   -0.713745
Name: 2020-08-02 00:00:00, dtype: float64

In [52]:
# 스칼라 값을 얻는다
df.loc[dates[0],'A']
# df.loc[dates[0],'A'] 위와 같은 결과

-0.1271626987097826

### Selection by Position (위치로 선택하기)

In [53]:
df

A         B         C         D
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776
2020-08-05  0.752654  1.366403 -1.470055 -1.165753
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065

In [55]:
df.iloc[3] # 3번째 행을 가져온다

A   -0.127509
B    0.248788
C   -1.974687
D   -0.652776
Name: 2020-08-04 00:00:00, dtype: float64

In [56]:
df.iloc[3:5, 0:2]

A         B
2020-08-04 -0.127509  0.248788
2020-08-05  0.752654  1.366403

In [57]:
df.iloc[[1,2,4],[0,2]]

A         C
2020-08-02 -1.617449  1.505878
2020-08-03  1.916352  0.329807
2020-08-05  0.752654 -1.470055

In [58]:
df.iloc[1:3,:]

A         B         C         D
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672
2020-08-03  1.916352 -1.080539  0.329807 -0.521748

In [59]:
df.iloc[:,1:3]

B         C
2020-08-01 -0.047479 -0.003089
2020-08-02 -0.713745  1.505878
2020-08-03 -1.080539  0.329807
2020-08-04  0.248788 -1.974687
2020-08-05  1.366403 -1.470055
2020-08-06 -0.800943 -0.356288

In [61]:
# 특정 값 출력
df.iloc[1,1]
# df.iat[1,1] 위와 동일한 결과

-0.713744697530221

### Boolean Indexing

In [62]:
df[df.A > 0] # A열의 값이 0을 넘는 행을 가져온다

A         B         C         D
2020-08-03  1.916352 -1.080539  0.329807 -0.521748
2020-08-05  0.752654  1.366403 -1.470055 -1.165753

In [64]:
df[df > 0]

A         B         C         D
2020-08-01       NaN       NaN       NaN       NaN
2020-08-02       NaN       NaN  1.505878       NaN
2020-08-03  1.916352       NaN  0.329807       NaN
2020-08-04       NaN  0.248788       NaN       NaN
2020-08-05  0.752654  1.366403       NaN       NaN
2020-08-06       NaN       NaN       NaN  0.007065

In [65]:
df2 = df.copy()

In [66]:
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three'] # E열 추가
df2

A         B         C         D      E
2020-08-01 -0.127163 -0.047479 -0.003089 -0.702017    one
2020-08-02 -1.617449 -0.713745  1.505878 -0.363672    one
2020-08-03  1.916352 -1.080539  0.329807 -0.521748    two
2020-08-04 -0.127509  0.248788 -1.974687 -0.652776  three
2020-08-05  0.752654  1.366403 -1.470055 -1.165753   four
2020-08-06 -0.480413 -0.800943 -0.356288  0.007065  three

In [68]:
df2[df2['E'].isin(['two','four'])] # df2의 E열 안에 two, four값이 있는 행만 출력

A         B         C         D     E
2020-08-03  1.916352 -1.080539  0.329807 -0.521748   two
2020-08-05  0.752654  1.366403 -1.470055 -1.165753  four

### Setting (설정)

In [71]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20200802', periods=6))
s1

2020-08-02    1
2020-08-03    2
2020-08-04    3
2020-08-05    4
2020-08-06    5
2020-08-07    6
Freq: D, dtype: int64

In [73]:
df['F'] = s1
df.at[dates[0],'A'] = 0 # dates[0]의 'A'열의 값에 0을 넣는다
df.iat[0,1] = 0 # [0,1]위치에 0값을 넣는다
df.loc[:,'D'] = np.array([5] * len(df))

In [74]:
df

A         B         C  D    F
2020-08-01  0.000000  0.000000 -0.003089  5  NaN
2020-08-02 -1.617449 -0.713745  1.505878  5  1.0
2020-08-03  1.916352 -1.080539  0.329807  5  2.0
2020-08-04 -0.127509  0.248788 -1.974687  5  3.0
2020-08-05  0.752654  1.366403 -1.470055  5  4.0
2020-08-06 -0.480413 -0.800943 -0.356288  5  5.0

In [75]:
df2 = df.copy()
df2[df2>0] = -df2
df2

A         B         C  D    F
2020-08-01  0.000000  0.000000 -0.003089 -5  NaN
2020-08-02 -1.617449 -0.713745 -1.505878 -5 -1.0
2020-08-03 -1.916352 -1.080539 -0.329807 -5 -2.0
2020-08-04 -0.127509 -0.248788 -1.974687 -5 -3.0
2020-08-05 -0.752654 -1.366403 -1.470055 -5 -4.0
2020-08-06 -0.480413 -0.800943 -0.356288 -5 -5.0